name: AIA Hong Kong
favicon: null
layout_spectrum: 0.7115485153626651
typography_spectrum: 0.22675487748347223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5208475550170988
  lightness: 0.43660955294035375
  saturation: 0.1321208442095667
  rhythmicContrast: 0.1786567447707057
purpose: []
